#include "cpu_util.h"

const byte_t instr_lookup[] =
    {OP_NOP, OP_LD_RR_NN, OP_LD_BCA, OP_INC_RR, OP_INC_R, OP_DEC_R, OP_LD_RN, OP_UNIMP, OP_LD_NN_SP, OP_ADD_HL_RR, OP_LD_RR, OP_DEC_RR, OP_INC_R, OP_DEC_R, OP_LD_RN, OP_UNIMP,
     OP_UNIMP, OP_LD_RR_NN, OP_LD_RR, OP_LD_DEA, OP_INC_RR, OP_INC_R, OP_DEC_R, OP_LD_RN, OP_UNIMP, OP_UNIMP, OP_ADD_HL_RR, OP_LD_ADE, OP_DEC_RR, OP_INC_R, OP_INC_R, OP_LD_RN, OP_UNIMP,
     OP_UNIMP, OP_LD_RR_NN, OP_LD_HLA_p, OP_INC_RR, OP_INC_R, OP_DEC_R, OP_LD_RN, OP_DAA, OP_UNIMP, OP_ADD_HL_RR, OP_LD_AHL_p, OP_DEC_RR, OP_INC_R, OP_DEC_R, OP_LD_RN, OP_UNIMP,
     };